---
- name: Target Installation
  hosts: target

  tasks:
  - name: Change motd saying Ansible Managed by student number of the server /etc/motd
    lineinfile:
      path: '/etc/motd'
      line: 'Ansible Managed by 1813462'
      state: present

  - name: Create a user with github
    user:
      name: fgfpenuliar-tip
      state: present
      password: AnsibleManaged

  - name: passwordless sudo user
    lineinfile:
      path: '/etc/sudoers'
      line: 'fgfpenuliar-tip ALL=(ALL) NOPASSWD: ALL'
      state: present

  - name: group sysad2 Quiz2
    group:
      name: sysad2
      state: present
